obj/GUIHandler.o: src/GUIHandler.c src/GUIHandler.h src/structs.h \
 src/enums.h src/dbHandler.h src/interactiveHandler.h src/errorHandler.h \
 src/commandHandler.h src/helper.h src/drunt.h
obj/drunt.o: src/drunt.c src/structs.h src/enums.h src/dbHandler.h \
 src/errorHandler.h src/helper.h src/interactiveHandler.h \
 src/commandHandler.h src/GUIHandler.h
obj/interactiveHandler.o: src/interactiveHandler.c src/drunt.h \
 src/structs.h src/enums.h src/interactiveHandler.h src/errorHandler.h \
 src/dbHandler.h src/commandHandler.h src/helper.h
obj/dbHandler.o: src/dbHandler.c src/dbHandler.h src/structs.h \
 src/enums.h src/errorHandler.h src/helper.h
obj/helper.o: src/helper.c src/helper.h src/structs.h src/enums.h \
 src/errorHandler.h
obj/commandHandler.o: src/commandHandler.c src/commandHandler.h \
 src/structs.h src/enums.h src/interactiveHandler.h src/errorHandler.h \
 src/dbHandler.h src/helper.h src/drunt.h
obj/errorHandler.o: src/errorHandler.c src/errorHandler.h
